### ISSUE TITLE
CLImate Roadmap

### ISSUE THREAD

**Issue by isaac-gros** [isaac-gros/CLImate-game#1]
# CLImate Roadmap
Main functionalities and progresses will be tracked here!
Work in progress for the data model [here](https://drive.google.com/file/d/1jmrkB5TKlzzl6wShcgFbruKVi3xVftda/view?usp=sharing).

## Game logic
- [ ] Reproduce a tree-view lookalike environment model `FileSystem`
- [ ] Create models for `FileSystem` entities : 
  - [ ] `Directory`
  - [ ] `File`
  - [ ] `Directory`
  - [ ] `User`
  - [ ] `Group`
- [ ] Create the `Player` model
- [ ] Create the `Tutorial` model 
- [ ] Code the UNIX commands interacting with the environment
  - [ ] `ls` with option(s) `-a, --all`
  - [ ] `cd`
  - [ ] `echo`
  - [ ] `whoami`
  - [ ] `rm` with option(s) `-f, --force`
  - [ ] `cat`
  - [ ] `tail`
  - [ ] `head`

## Game UI
The game should use pixel art.
- [ ] Player sprites
  - [ ] Still
  - [ ] Running
  - [ ] Aiming
- [ ] Files and directories appearances 
- [ ] Game backgrounds
  - [ ] Ground
  - [ ] Walls
  - [ ] Doors (?)

## Back-end
- [x] Choose a database system
- [x] Create Docker configuration
- [ ] Back-office with login/password
- [ ] Implement custom level editor

## In the future...
~~- Implement custom level editor~~ (will be a part of the game)
